export async function GET() {
    const allHotels = [
      {
        id: 1,
        name: 'Urbanza Suites',
        location: 'Main Road 123 Street, 23 Colony',
        image: '/Assets/hotels/hotel1.jpg',
        rating: 3.6,
        price: 199,
        tag: 'Best Seller',
      },
      {
        id: 2,
        name: 'Luxe Stay Inn',
        location: 'Beach Road, Goa',
        image: '/Assets/hotels/hotel2.jpg',
        rating: 4.7,
        price: 299,
        tag: 'Popular',
      },
      {
        id: 3,
        name: 'Haven Residency',
        location: 'Lakeview Boulevard',
        image: '/Assets/hotels/hotel3.jpg',
        rating: 4.2,
        price: 249,
        tag: '',
      },
      {
        id: 4,
        name: 'Royal Heritage Hotel',
        location: 'Rajpath, Jaipur',
        image: '/Assets/hotels/hotel4.jpg',
        rating: 4.6,
        price: 299,
        tag: 'Trending',
      },
      {
        id: 5,
        name: 'Coastal Comfort Resort',
        location: 'Marina Beach, Chennai',
        image: '/Assets/hotels/hotel5.jpg',
        rating: 4.7,
        price: 359,
        tag: 'Luxury',
      },
      {
        id: 6,
        name: 'Mountain Escape',
        location: 'Shimla Hills',
        image: '/Assets/hotels/hotel6.jpg',
        rating: 4.8,
        price: 399,
        tag: 'Scenic',
      },
      {
        id: 7,
        name: 'City Central Hotel',
        location: 'Connaught Place, Delhi',
        image: '/Assets/hotels/hotel7.jpg',
        rating: 4.9,
        price: 429,
        tag: 'Premium',
      },
      {
        id: 8,
        name: 'The Palms',
        location: 'MG Road, Bangalore',
        image: '/Assets/hotels/hotel8.jpg',
        rating: 3.9,
        price: 199,
        tag: '',
      },
      {
        id: 9,
        name: 'Snowpeak Lodge',
        location: 'Manali Heights',
        image: '/Assets/hotels/hotel9.jpg',
        rating: 4.6,
        price: 355,
        tag: 'Top Pick',
      },
      {
        id: 10,
        name: 'The Sunset Villa',
        location: 'Alleppey Backwaters',
        image: '/Assets/hotels/hotel10.jpg',
        rating: 4.2,
        price: 260,
        tag: '',
      },
      {
        id: 11,
        name: 'Golden Petals Resort',
        location: 'Udaipur',
        image: '/Assets/hotels/hotel11.jpg',
        rating: 4.7,
        price: 450,
        tag: 'Romantic',
      },
      {
        id: 12,
        name: 'Harbor View Inn',
        location: 'Mumbai Coastline',
        image: '/Assets/hotels/hotel12.jpg',
        rating: 4.3,
        price: 370,
        tag: '',
      },
      {
        id: 13,
        name: 'Palm Grove Hotel',
        location: 'Kovalam Beach, Kerala',
        image: '/Assets/hotels/hotel13.jpg',
        rating: 4.5,
        price: 390,
        tag: 'Beachside',
      },
      {
        id: 14,
        name: 'Moonlight Residency',
        location: 'Leh, Ladakh',
        image: '/Assets/hotels/hotel14.jpg',
        rating: 4.9,
        price: 459,
        tag: 'Scenic',
      },
      {
        id: 15,
        name: 'Silken Sands Hotel',
        location: 'Pondicherry Promenade',
        image: '/Assets/hotels/hotel15.jpg',
        rating: 4.3,
        price: 325,
        tag: 'Peaceful',
      },
      {
        id: 16,
        name: 'The Heritage Stay',
        location: 'Old Fort Road, Jodhpur',
        image: '/Assets/hotels/hotel16.jpg',
        rating: 4.2,
        price: 285,
        tag: '',
      },
      {
        id: 17,
        name: 'Lake View Palace',
        location: 'Nainital Lakefront',
        image: '/Assets/hotels/hotel17.jpg',
        rating: 4.8,
        price: 399,
        tag: 'Scenic',
      },
      {
        id: 18,
        name: 'Bamboo Retreat',
        location: 'Darjeeling',
        image: '/Assets/hotels/hotel18.jpg',
        rating: 4.3,
        price: 325,
        tag: '',
      },
      {
        id: 19,
        name: 'Coconut Bay Hotel',
        location: 'Goa',
        image: '/Assets/hotels/hotel19.jpg',
        rating: 4.6,
        price: 410,
        tag: 'Relaxing',
      },
      {
        id: 20,
        name: 'The Royal Orchid',
        location: 'Lucknow',
        image: '/Assets/hotels/hotel20.jpg',
        rating: 4.9,
        price: 540,
        tag: 'Top Rated',
      },
    ];
  
    return Response.json(allHotels);
  }
  