export async function GET() {
  const allHotels = [
    {
      id: 1,
      name: 'Urbanza Suites',
      location: 'Main Road 123 Street, 23 Colony',
      image: '/Assets/hotels/hotel1.jpg',
      rating: 3.6,
      price: 2250,
      tag: 'Best Seller',
      maxGuests: 2,
      description: "Urbanza Suites offers cozy and budget-friendly accommodations right in the heart of 23 Colony. Perfect for travelers seeking comfort without breaking the bank, with easy access to local attractions and vibrant street life.",
      services: "Enjoy complimentary Wi-Fi, air conditioning, round-the-clock room service, and tasty in-house dining. Ideal for solo adventurers, couples, and small families looking for convenience and value."
    },
    {
      id: 2,
      name: 'Luxe Stay Inn',
      location: 'Beach Road, Goa',
      image: '/Assets/hotels/hotel2.jpg',
      rating: 4.7,
      price: 3100,
      tag: 'Popular',
      maxGuests: 3,
      description: "Luxe Stay Inn is a chic beachside retreat on Goa’s famous Beach Road, blending modern luxury with laid-back coastal vibes. Guests love the stylish interiors and proximity to the vibrant nightlife and sandy shores.",
      services: "Facilities include high-speed Wi-Fi, air conditioning, 24/7 room service, in-house dining, and complimentary breakfast. Perfect for beach lovers, couples, and groups seeking a lively getaway."
    },
    {
      id: 3,
      name: 'Haven Residency',
      location: 'Lakeview Boulevard',
      image: '/Assets/hotels/hotel3.jpg',
      rating: 4.2,
      price: 2000,
      tag: '',
      maxGuests: 2,
      description: "Nestled along serene Lakeview Boulevard, Haven Residency offers peaceful stays with stunning water views. A great choice for those wanting a quiet escape with easy access to outdoor activities and local charm.",
      services: "Guests can enjoy free Wi-Fi, air conditioning, 24/7 room service, laundry facilities, and boat rentals. Ideal for nature enthusiasts, couples, and families looking to unwind."
    },
    {
      id: 4,
      name: 'Royal Heritage Hotel',
      location: 'Rajpath, Jaipur',
      image: '/Assets/hotels/hotel4.jpg',
      rating: 4.6,
      price: 2900,
      tag: 'Trending',
      maxGuests: 3,
      description: "Step into the grandeur of Royal Heritage Hotel, where Rajasthan’s rich culture meets modern comfort. Situated on Rajpath, Jaipur, this hotel is a favorite for travelers eager to explore historic sites with style.",
      services: "Offering free Wi-Fi, air conditioning, 24/7 room service, traditional in-house dining, and complimentary breakfast. Perfect for culture seekers, families, and history buffs."
    },
    {
      id: 5,
      name: 'Coastal Comfort Resort',
      location: 'Marina Beach, Chennai',
      image: '/Assets/hotels/hotel5.jpg',
      rating: 4.7,
      price: 4750,
      tag: 'Luxury',
      maxGuests: 4,
      description: "Coastal Comfort Resort is a luxurious beachfront haven on Marina Beach, Chennai. Enjoy elegant rooms with panoramic sea views and premium amenities designed for relaxation and indulgence.",
      services: "Facilities feature free Wi-Fi, air conditioning, 24/7 room service, gourmet in-house dining, spa services, and private beach access. Ideal for honeymooners, families, and luxury travelers."
    },
    {
      id: 6,
      name: 'Mountain Escape',
      location: 'Shimla Hills',
      image: '/Assets/hotels/hotel6.jpg',
      rating: 4.8,
      price: 4350,
      tag: 'Scenic',
      maxGuests: 3,
      description: "Mountain Escape invites you to breathe fresh mountain air and enjoy breathtaking views in Shimla Hills. Perfect for those seeking tranquility, adventure, and a touch of luxury amidst nature.",
      services: "Enjoy complimentary Wi-Fi, air conditioning, 24/7 room service, spa treatments, guided hiking tours, and cozy in-house dining. Perfect for nature lovers and adventure seekers alike."
    },
    {
      id: 7,
      name: 'City Central Hotel',
      location: 'Connaught Place, Delhi',
      image: '/Assets/hotels/hotel7.jpg',
      rating: 4.9,
      price: 5400,
      tag: 'Premium',
      maxGuests: 2,
      description: "Located in the bustling heart of Delhi, City Central Hotel offers premium accommodations with top-notch amenities. Experience luxury and convenience steps away from Connaught Place’s shopping and dining hotspots.",
      services: "Features include high-speed Wi-Fi, air conditioning, 24/7 room service, exclusive lounge access, spa facilities, and personalized concierge. Ideal for business travelers and discerning guests."
    },
    {
      id: 8,
      name: 'The Palms',
      location: 'MG Road, Bangalore',
      image: '/Assets/hotels/hotel8.jpg',
      rating: 3.9,
      price: 2150,
      tag: '',
      maxGuests: 2,
      description: "The Palms offers affordable comfort in the vibrant MG Road area of Bangalore. A great base for exploring the city’s tech hubs and cultural sites with easy access to public transport.",
      services: "Enjoy free Wi-Fi, air conditioning, 24/7 room service, and cozy dining options. Suitable for budget-conscious travelers, solo visitors, and business guests."
    },
    {
      id: 9,
      name: 'Snowpeak Lodge',
      location: 'Manali Heights',
      image: '/Assets/hotels/hotel9.jpg',
      rating: 4.6,
      price: 3950,
      tag: 'Top Pick',
      maxGuests: 3,
      description: "Snowpeak Lodge is a top pick for travelers visiting Manali Heights, offering warm hospitality and stunning mountain views. A perfect retreat after a day of exploring the Himalayas.",
      services: "Facilities include free Wi-Fi, air conditioning, 24/7 room service, hearty in-house dining, and complimentary breakfast. Ideal for adventure lovers and families."
    },
    {
      id: 10,
      name: 'The Sunset Villa',
      location: 'Alleppey Backwaters',
      image: '/Assets/hotels/hotel10.jpg',
      rating: 4.2,
      price: 2350,
      tag: '',
      maxGuests: 2,
      description: "Relax at The Sunset Villa, nestled along the tranquil Alleppey Backwaters. Enjoy peaceful surroundings, traditional Kerala hospitality, and beautiful sunset views.",
      services: "Guests enjoy free Wi-Fi, air conditioning, 24/7 room service, in-house dining, and complimentary breakfast. Perfect for couples and families seeking serenity."
    },
    {
      id: 11,
      name: 'Golden Petals Resort',
      location: 'Udaipur',
      image: '/Assets/hotels/hotel11.jpg',
      rating: 4.7,
      price: 4250,
      tag: 'Romantic',
      maxGuests: 2,
      description: "Golden Petals Resort in Udaipur is a romantic getaway with luxurious rooms and stunning lake views. Ideal for couples looking to celebrate special moments in style.",
      services: "Enjoy free Wi-Fi, air conditioning, 24/7 room service, spa treatments, private pool access, and gourmet dining. Perfect for honeymooners and romantic escapes."
    },
    {
      id: 12,
      name: 'Harbor View Inn',
      location: 'Mumbai Coastline',
      image: '/Assets/hotels/hotel12.jpg',
      rating: 4.3,
      price: 2500,
      tag: '',
      maxGuests: 3,
      description: "Harbor View Inn offers modern comfort with spectacular views of the Mumbai coastline. A great choice for travelers wanting to explore the city’s vibrant waterfront.",
      services: "Facilities include free Wi-Fi, air conditioning, 24/7 room service, in-house dining, and complimentary breakfast. Ideal for business travelers and tourists."
    },
    {
      id: 13,
      name: 'Palm Grove Hotel',
      location: 'Kovalam Beach, Kerala',
      image: '/Assets/hotels/hotel13.jpg',
      rating: 4.5,
      price: 3900,
      tag: 'Beachside',
      maxGuests: 4,
      description: "Palm Grove Hotel is a charming beachside property in Kovalam, Kerala. Enjoy the gentle sea breeze, palm-lined shores, and warm hospitality.",
      services: "Guests can enjoy free Wi-Fi, air conditioning, 24/7 room service, in-house dining, beach access, and water sports. Perfect for beach lovers and families."
    },
    {
      id: 14,
      name: 'Moonlight Residency',
      location: 'Leh, Ladakh',
      image: '/Assets/hotels/hotel14.jpg',
      rating: 4.9,
      price: 4750,
      tag: 'Scenic',
      maxGuests: 2,
      description: "Moonlight Residency offers breathtaking views of the Ladakh mountains. Experience peaceful luxury and authentic local culture in the heart of Leh.",
      services: "Enjoy free Wi-Fi, air conditioning, 24/7 room service, spa treatments, scenic guided tours, and in-house dining. Ideal for nature lovers and cultural explorers."
    },
    {
      id: 15,
      name: 'Silken Sands Hotel',
      location: 'Pondicherry Promenade',
      image: '/Assets/hotels/hotel15.jpg',
      rating: 4.3,
      price: 3450,
      tag: 'Peaceful',
      maxGuests: 2,
      description: "Silken Sands Hotel offers a tranquil stay along the Pondicherry Promenade, perfect for guests seeking relaxation and calm by the sea.",
      services: "Facilities include free Wi-Fi, air conditioning, 24/7 room service, in-house dining, and quiet meditation spaces. Ideal for solo travelers and couples."
    },
    {
      id: 16,
      name: 'The Heritage Stay',
      location: 'Old Fort Road, Jodhpur',
      image: '/Assets/hotels/hotel16.jpg',
      rating: 4.2,
      price: 2650,
      tag: '',
      maxGuests: 3,
      description: "The Heritage Stay captures the essence of Jodhpur’s rich history with traditional architecture and warm hospitality on Old Fort Road.",
      services: "Guests enjoy free Wi-Fi, air conditioning, 24/7 room service, in-house dining, and cultural tours. Perfect for history buffs and families."
    },
    {
      id: 17,
      name: 'Lake View Palace',
      location: 'Nainital Lakefront',
      image: '/Assets/hotels/hotel17.jpg',
      rating: 4.8,
      price: 4900,
      tag: 'Scenic',
      maxGuests: 4,
      description: "Lake View Palace offers regal accommodations with stunning views of Nainital Lake. A luxurious retreat for those wanting to unwind in nature’s beauty.",
      services: "Facilities include free Wi-Fi, air conditioning, 24/7 room service, in-house dining, guided boat tours, and butler service. Ideal for luxury seekers and nature lovers."
    },
    {
      id: 18,
      name: 'Bamboo Retreat',
      location: 'Darjeeling',
      image: '/Assets/hotels/hotel18.jpg',
      rating: 4.3,
      price: 2800,
      tag: '',
      maxGuests: 2,
      description: "Bamboo Retreat offers cozy stays surrounded by lush greenery in Darjeeling. A peaceful spot for travelers wanting to explore tea gardens and mountain trails.",
      services: "Enjoy free Wi-Fi, air conditioning, 24/7 room service, in-house dining, and complimentary breakfast. Great for solo travelers and nature enthusiasts."
    },
    {
      id: 19,
      name: 'Coconut Bay Hotel',
      location: 'Goa',
      image: '/Assets/hotels/hotel19.jpg',
      rating: 4.6,
      price: 4450,
      tag: 'Relaxing',
      maxGuests: 3,
      description: "Coconut Bay Hotel in Goa is a serene oasis offering luxurious amenities and a laid-back vibe. Perfect for guests looking to relax and rejuvenate by the sea.",
      services: "Facilities include free Wi-Fi, air conditioning, 24/7 room service, spa treatments, private pool, and yoga classes. Ideal for wellness seekers and couples."
    },
    {
      id: 20,
      name: 'The Royal Orchid',
      location: 'Lucknow',
      image: '/Assets/hotels/hotel20.jpg',
      rating: 4.9,
      price: 6550,
      tag: 'Top Rated',
      maxGuests: 2,
      description: "The Royal Orchid in Lucknow epitomizes luxury and elegance with impeccable service and refined décor. A top-rated choice for discerning travelers.",
      services: "Guests enjoy free Wi-Fi, air conditioning, 24/7 room service, spa and wellness center, private pool, and VIP concierge services. Perfect for luxury travelers and special occasions."
    }
  ];

  return Response.json(allHotels);
}
